# ---------------- Stage 1: Builder -----------------
FROM python:3.13-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# ------------------ Stage 2: Runtime ---------------
FROM python:3.13-slim AS runtime
RUN useradd -u 10001 christopher
WORKDIR /app
COPY --from=builder /install .
ENV PATH="/install:$PATH"
COPY . .
USER 10001
EXPOSE 5000
CMD ["python", "app.py"]
